default:
    go run *.go || (go get ./... && go run *.go)

build:
    just schema-const
    sqlc generate

test: build
    go test ./... -count 1

watch:
    #!/usr/bin/env bash
    (watchexec -e sql -- just schema-const) & \
    (watchexec -e sql -- sqlc generate) & \
    (watchexec -w sqlc.yaml -- sqlc generate) & \
    (watchexec -e go -c -r -- go test ./... -count 1) & \
    wait
    # SQL Watcher done

# Puts the schema in a constant in go so it can be used to create the table directly
schema-const:
    echo "// Code generated by justfile. DO NOT EDIT." > internal/schema.go
    printf "package internal\n\n" >> internal/schema.go
    echo "const Schema = \`" >> internal/schema.go
    cat db/schema.sql >> internal/schema.go
    echo "\`" >> internal/schema.go

bench: cleanup schema-const
    sqlc generate
    cd bench && go run main.go

cleanup:
    rm -f bench/bench.db*
